name = "cf-r2-webdav"
main = "src/index.ts"
compatibility_date = "2023-01-01"

[vars]
# 环境变量将在部署时由 GitHub Actions 提供
# USERNAME = ""
# PASSWORD = ""
# BUCKET_NAME = ""

[[r2_buckets]]
binding = "BUCKET"