name = "webdav-s3-server"
main = "src/index.ts"
compatibility_date = "2023-01-01"

[vars]
USERNAME = "user"
PASSWORD = "pass"

[[r2_buckets]]
binding = "bucket"
bucket_name = "n8n"

[vars.S3]
ENDPOINT = "your_s3_endpoint"
REGION = "auto"
ACCESS_KEY_ID = "your_access_key_id"
SECRET_ACCESS_KEY = "your_secret_access_key"
BUCKET = "n8n"